'use strict';

const { test, expect } = require('../../fixtures');

/**
 * Partner Site Order Status & BOL Verification Tests.
 *
 * Verifies that order statuses from HoodslyHub / WRH Hub are reflected correctly
 * on the partner WordPress site's WooCommerce orders, and that BOL tracking numbers
 * generated by RL Carrier are visible on the partner order detail page.
 *
 * Required env vars:
 *  - PARTNER_SITE_BASE_URL  — partner WordPress site base URL
 *  - TEST_ORDER_NUMBER      — a real WooCommerce order number to verify (optional; tests skip if absent)
 */
test.describe('Partner Site — Order Status & BOL Verification', () => {
  test.beforeEach(async ({ page }) => {
    const partnerUrl = process.env.PARTNER_SITE_BASE_URL;
    if (!partnerUrl) {
      test.skip(true, 'PARTNER_SITE_BASE_URL not configured — skipping partner site tests');
      return;
    }
    await page.goto(`${partnerUrl}/wp-admin/`);
  });

  test('WooCommerce orders list is accessible from partner site admin', async ({
    partnerSiteOrdersPage,
  }) => {
    await partnerSiteOrdersPage.navigateToOrders();
    await expect(partnerSiteOrdersPage.page).toHaveURL(/wc-orders|shop_order/);
  });

  test('order search input is visible on orders list page', async ({
    partnerSiteOrdersPage,
  }) => {
    await partnerSiteOrdersPage.navigateToOrders();
    await expect(partnerSiteOrdersPage.orderSearchInput).toBeVisible();
  });

  test('searching for an order by number renders the orders list', async ({
    partnerSiteOrdersPage,
  }) => {
    const orderNumber = process.env.TEST_ORDER_NUMBER;
    if (!orderNumber) {
      test.skip(true, 'TEST_ORDER_NUMBER not set — skipping order search');
      return;
    }
    await partnerSiteOrdersPage.navigateToOrders();
    await partnerSiteOrdersPage.searchOrder(orderNumber);
    await expect(partnerSiteOrdersPage.page).toHaveURL(/wc-orders|shop_order/);
  });

  test('order detail page shows RL Carrier tracking number for BOL order', async ({
    partnerSiteOrdersPage,
  }) => {
    const orderNumber = process.env.TEST_ORDER_NUMBER;
    if (!orderNumber) {
      test.skip(true, 'TEST_ORDER_NUMBER not set — skipping BOL tracking number check');
      return;
    }
    await partnerSiteOrdersPage.navigateToOrders();
    await partnerSiteOrdersPage.searchOrder(orderNumber);
    await partnerSiteOrdersPage.openOrderByNumber(orderNumber);
    const trackingNumber = await partnerSiteOrdersPage.getTrackingNumber();
    expect(trackingNumber).toBeTruthy();
    expect(trackingNumber.length).toBeGreaterThan(0);
  });

  test('order status is readable from partner site WooCommerce order detail', async ({
    partnerSiteOrdersPage,
  }) => {
    const orderNumber = process.env.TEST_ORDER_NUMBER;
    if (!orderNumber) {
      test.skip(true, 'TEST_ORDER_NUMBER not set — skipping order status read');
      return;
    }
    await partnerSiteOrdersPage.navigateToOrders();
    await partnerSiteOrdersPage.searchOrder(orderNumber);
    await partnerSiteOrdersPage.openOrderByNumber(orderNumber);
    const status = await partnerSiteOrdersPage.getOrderStatus();
    expect(status).toBeTruthy();
    expect(status.length).toBeGreaterThan(0);
  });

  test('order status sync — status matches expected value after hub update', async ({
    partnerSiteOrdersPage,
  }) => {
    const orderNumber = process.env.TEST_ORDER_NUMBER;
    const expectedStatus = process.env.EXPECTED_ORDER_STATUS;
    if (!orderNumber || !expectedStatus) {
      test.skip(
        true,
        'TEST_ORDER_NUMBER and EXPECTED_ORDER_STATUS must both be set for status sync verification'
      );
      return;
    }
    await partnerSiteOrdersPage.navigateToOrders();
    await partnerSiteOrdersPage.searchOrder(orderNumber);
    await partnerSiteOrdersPage.openOrderByNumber(orderNumber);
    const status = await partnerSiteOrdersPage.getOrderStatus();
    expect(status).toBe(expectedStatus);
  });
});
